version: '2.0'

services:

  app:
    container_name: link_repo
    build: .
    ports:
    - "3001:3001"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules

  database:
    container_name: database
    image: postgres
    ports:
    - "5430:5432"
    environment:
      POSTGRES_DB: links_repo
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
